//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchFinding) DeepCopyInto(out *DispatchFinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchFinding.
func (in *DispatchFinding) DeepCopy() *DispatchFinding {
	if in == nil {
		return nil
	}
	out := new(DispatchFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DispatchFinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchFindingList) DeepCopyInto(out *DispatchFindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DispatchFinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchFindingList.
func (in *DispatchFindingList) DeepCopy() *DispatchFindingList {
	if in == nil {
		return nil
	}
	out := new(DispatchFindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DispatchFindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchFindingSpec) DeepCopyInto(out *DispatchFindingSpec) {
	*out = *in
	out.Subject = in.Subject
	if in.Related != nil {
		in, out := &in.Related, &out.Related
		*out = make([]DispatchFindingSubject, len(*in))
		copy(*out, *in)
	}
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchFindingSpec.
func (in *DispatchFindingSpec) DeepCopy() *DispatchFindingSpec {
	if in == nil {
		return nil
	}
	out := new(DispatchFindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchFindingStatus) DeepCopyInto(out *DispatchFindingStatus) {
	*out = *in
	in.FirstSeen.DeepCopyInto(&out.FirstSeen)
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchFindingStatus.
func (in *DispatchFindingStatus) DeepCopy() *DispatchFindingStatus {
	if in == nil {
		return nil
	}
	out := new(DispatchFindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchFindingSubject) DeepCopyInto(out *DispatchFindingSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchFindingSubject.
func (in *DispatchFindingSubject) DeepCopy() *DispatchFindingSubject {
	if in == nil {
		return nil
	}
	out := new(DispatchFindingSubject)
	in.DeepCopyInto(out)
	return out
}
